### ISSUE TITLE
Script freeze

### ISSUE THREAD

**Issue by Welkiki** [TrainerRoshi/Roshi-HHeroes-Trainer#16]
Script freeze on club champion page and can't turn off the option. I deleted ookies, nothing changed. I'd like to reset config so i can turn off this option but can't where settings are saved :/ 
![Capture](https://user-images.githubusercontent.com/79487506/108786885-eb57fb80-7574-11eb-8730-6287f7bbebff.PNG)

I'm using Edge

**Comment by Welkiki** [comment]
Just had to delete local storage my bad

**Comment by TrainerRoshi** [comment]
Don't turn it on. I had no clue anyone under level 100 even used my scripts. Sorry about that. I'll add some checks in a future update to hide options if your level is too low.

**Comment by Welkiki** [comment]
I created a new account to take the screenshot, Same problem with main account on my  2 computers.

Still using edge on both

**Comment by TrainerRoshi** [comment]
Do this first:
![Screenshot (63)](https://user-images.githubusercontent.com/48032437/108890995-3527fc80-75dc-11eb-9bec-613c8993a463.png)
Then do this:
![Screenshot (65)](https://user-images.githubusercontent.com/48032437/108891030-3d803780-75dc-11eb-87b2-98dfade1b8a0.png)
This will solve your problems with any website on the Internet.

**Comment by Welkiki** [comment]
Just did this, when i activate the club option same thing occurs: it opens the club page on the champion tab.
When i click challenge  the script seem to go on, but then come back to the club page on champion tab

**Comment by TrainerRoshi** [comment]
Why are you clicking <challenge> ? Don't click anything. Either you do it manually or you let it run auto, not both.

**Comment by Welkiki** [comment]
i click cause it doesn't do anything if i don't 
turned off all other scripts then deleted local/session/cookies still persists

**Comment by TrainerRoshi** [comment]
What does the console say? Copy/Paste or post a screen capture please.

**Comment by Welkiki** [comment]
I manually click cause nothing happens.

I turned off all other scripts, reseted local, session and cookies, it still persists

**Comment by TrainerRoshi** [comment]
I just tested it in Microsoft Edge 44.18362.449.0 (Microsoft EdgeHTML 18.18363) and everything works. Try closing all your browsers and opening them again.

**Comment by Welkiki** [comment]
I'm on edge 88.0.705.74 i tryed that, didn't worked, also tried on freshly installed chrome, same result (HH doesn't really work for me on firefox so can't really try)

**Comment by TrainerRoshi** [comment]
I design it on chrome, so it should work. Unless I see what the console says, I can't tell where the script stops working. 
![Screenshot (67)](https://user-images.githubusercontent.com/48032437/109047014-60295380-76a3-11eb-8663-9381a53f2db6.png)

**Comment by Welkiki** [comment]
![image](https://user-images.githubusercontent.com/79487506/109048399-53265780-76d7-11eb-8c6a-6c6f11888d69.png)

**Comment by TrainerRoshi** [comment]
Fixed as of 1.15.5. My bad, I should have asked to see your console from the start.

**Comment by Welkiki** [comment]
np and ty for your work

closing the topic

**Comment by Welkiki** [comment]
closed too soon getting same console error

![image](https://user-images.githubusercontent.com/79487506/109065792-64c62a00-76ec-11eb-9316-af96e77d2efe.png)

**Comment by TrainerRoshi** [comment]
Balls. I really need to see more. You're giving me the absolute bare minimum. If I don't know what page you're on, I can't tell much from the console. Email me a screenshot at chef.roshi@gmail.com. I need more lines of the console and to see the game page, specifically the reward icons. And check your local storage, what is the value for club_reward_image and for club_reward_count ?

**Comment by TrainerRoshi** [comment]
Ok, try 1.15.6. That should fix things.

**Comment by Welkiki** [comment]
![image](https://user-images.githubusercontent.com/79487506/109076594-1ec49280-76fb-11eb-8865-c9d81f85d5c3.png)
 still not :/

**Comment by Welkiki** [comment]
From the very first picture i shared you can see i don't have the sub menus for market, champion, troll or club while on the club page.
And now i just noticed even when the script does not goes on that page i still don't have the sub menus

On main page
![image](https://user-images.githubusercontent.com/79487506/109080755-677f4a00-7701-11eb-9538-c2075a0221f5.png)

On club page
![image](https://user-images.githubusercontent.com/79487506/109080813-7cf47400-7701-11eb-8b51-736b16646ca7.png)

**Comment by TrainerRoshi** [comment]
Fixed as of 1.15.7. I hope that fixes your auto club freeze. I finally figured out the issue thanks to the screenshot with the longer console. 

As for the aesthetics of my menu, I would need to debug my CSS code on many different browsers and versions and it is not worth the effort yet. Since 2019 when I made this code public, I only know of exactly six people who use my script, plus you and me. You can see the nicknames of those six people in the hidden menu when you click on Roshi's face.

**Comment by mudasir370** [comment]
Still not fixed. Script only freezes when club is activated. And then sub-menu disappears & it keeps going back to club but do nothing. I'm on Opera.
![image](https://user-images.githubusercontent.com/79626383/109114808-f753e100-775f-11eb-9872-c95958358c54.png)
![image](https://user-images.githubusercontent.com/79626383/109115016-43068a80-7760-11eb-9ca7-ddff46808462.png)

**Comment by Welkiki** [comment]
![image](https://user-images.githubusercontent.com/79487506/109133866-b9ea5600-7755-11eb-8a0f-bb535f75b119.png)

the weirdest thing is it works for most ppl but not for me :/

**Comment by TrainerRoshi** [comment]
Try 1.15.8. I deleted the icon update. I wanted to show how many hearts you have in the trainer menu, but since I got the girl on all my test accounts I can't debug it properly. I'll add it back next season. Sorry about that.

**Comment by Welkiki** [comment]
1.15.8 Seem to work, thx for the amazing job.

I hope i didn't annoyed you too much with this issue.
Should be safe to close now

**Comment by Welkiki** [comment]
I'm really sorry but when i checked last time champ was defeated and resting, now that i can fight it script is in an infinite loop while  i have the Hentai Heroes++ (OCD) Season version 0.22.0 QoL script on.
Reason is it change the button on club page (not on champion page where you can change the girls fighting) when it's on cooldown. 
Instead of having the Skip using kobans it replace it with a link to champion page.

Without 
![image](https://user-images.githubusercontent.com/79487506/109329214-9a892100-785a-11eb-99e6-2061d2eab0a1.png)

With
![image](https://user-images.githubusercontent.com/79487506/109329275-ad035a80-785a-11eb-8783-fa98b2133f34.png)

Don't think you can do anything about it, just wanted it to be noted somewhere ^^'

**Comment by TrainerRoshi** [comment]
Why do people like that Hentai Heroes++ script? It just shows so much useless information. And most of it is super incorrect like where it shows the value of your items. The game only loads 100 items from the server at a time, so it is impossible to know the total. My script even shows how much affection you have with all the girls you can get in pachinko, the Hentai Heroes++ developer was too lazy to include even that. Let me know what you really like from Hentai Heroes++ and I'll include it in Roshi's script so you don't have to use both at the same time.
And I can make the blue Challenge button permanently visible if you want. Below is how you can manually do it yourself; add `style="display: block;"` to any container or button and it will be visible. In the video I'm changing `none;` to `block;`

https://user-images.githubusercontent.com/48032437/109347536-4de51c00-7841-11eb-8b60-1b2defa34f7c.mp4

**Comment by Welkiki** [comment]
As far as i'm concerned there are few features why i'm using the HH++:
-the 4 additional and the upgraded bars on main pages are usefull (easy link to champ, story/energy exchange and the fight counts for league and season)
-the battle sim, for almost every opponent it shows the result of a battle with lowest proc rate
-the name of girls in pachinko, mainly for mythic one, can check girl's wiki page in one click. I mainly check it to see girls max star and if they're available permanently in epic pachinko.
-the number of shards on girl's bubble (troll and pachinko)
-harem info, shows the total (or per girl) required amount of exp and affection (even per star is kinda useful)

I think that's it for me, but maybe you should ask that in a public discussion to have more point of view ?
